name: Frontend CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
        working-directory: ./frontend
    - name: build react app
      run: |
        pwd
        npm ci
        npm run build
    - name: Yandex object storage static website
      uses: NekitCorp/yandex-storage-website-action@v1
      with:        
        accessKeyId: ${{secrets.YC_SERVICE_ACCOUNT_ACCESS_KEY_ID}}
        secretAccessKey: ${{secrets.YC_SERVICE_ACCOUNT_ACCESS_KEY}}
        bucket: www.nextcloud.ru
        path: ./frontend/build        
        clear: true

