name: Frontend CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./frontend
    
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    
    - name: build react app
      run: |
        pwd
        npm ci
        npm run build
        
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --delete
      env:
        AWS_S3_ENDPOINT: https://storage.yandexcloud.net
        AWS_S3_BUCKET: www.nexusbook.ru
        AWS_ACCESS_KEY_ID: ${{secrets.YC_SERVICE_ACCOUNT_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.YC_SERVICE_ACCOUNT_ACCESS_KEY}}
        AWS_REGION: ru-central1
        SOURCE_DIR: ./frontend/build
